export const REQUEST_ERRORS = {
    MISSING_FIELDS: 100
}

export const USER_ERRORS = {
    ALREADY_LOGGED_IN: 200,
    DOES_NOT_EXIS: 201,
    INVALID_CREDENTIALS: 202,
    NOT_LOGGED_IN: 203,
    PERMISSION_DENIED: 204
}

export const RECIPE_ERRORS = {
    CREATION_FAILED: 300,
    DOES_NOT_EXIST: 301
}